### PR TITLE
Incorporate Material UI on Welcome page

### PR DESCRIPTION
**Pull request by cafloyd**
_For an example of how to fill this template out, [see this Pull Request](https://github.com/the-collab-lab/tcl-3-smart-shopping-list/pull/44)._ 

## Description

Incorporate Material UI components (Button, TextField) into Welcome page (`Welcome.js`/ `ShareToken.js`)

**_(styling to come!)_**

## Related Issue

#14 

## Acceptance Criteria

- As a user, I want the the app to look professional and welcoming

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|  ✓  | :hammer: Refactoring       |

### Before

image

### After

image

## Testing Steps / QA Criteria

To test the feature, use one of the following ways:

**(Make sure to open the page in incognito mode, or delete the token from your local storage in order to be directed to the welcome screen)**

1. Follow the [preview link](https://tcl-22-shopping-list--pr47-cf-material-ui-welco-1fukodsg.web.app/)
2. Launch the app locally from your terminal:
- Pull down this branch with `git pull origin cf-material-ui-welcome` and check that branch out with `git checkout origin cf-material-ui-welcome`
- Run npm start to launch the app in your browser at http://localhost:3000

### CODE REVIEW

**Comment by cafloyd** [comment]
Partially leaving this as a note to self to continue to investigate tomorrow, but also if anyone has input, feel free to chime in!

Can't figure out where to put the `required` that we had on the TextField in `ShareToken.js` - have tried leaving it in `ShareToken.js` as well as moving it to `components/TextField/TextField.js`, and neither implementation seems to be effectively requiring the text input, as I am able to click the "Join an existing list" button with no text input, which breaks the app.

I'm now thinking this is likely because I had to change the aforementioned "Join an existing list" button from an `<Input type=submit>` to a `<button>` in order to incorporate Material UI (didn't look like MUI had a specifically designated submit button).

Will continue investigating tomorrow!

**Comment by dariatsvetkova** [comment]
> Partially leaving this as a note to self to continue to investigate tomorrow, but also if anyone has input, feel free to chime in!
> 
> Can't figure out where to put the `required` that we had on the TextField in `ShareToken.js` - have tried leaving it in `ShareToken.js` as well as moving it to `components/TextField/TextField.js`, and neither implementation seems to be effectively requiring the text input, as I am able to click the "Join an existing list" button with no text input, which breaks the app.
> 
> I'm now thinking this is likely because I had to change the aforementioned "Join an existing list" button from an `<Input type=submit>` to a `<button>` in order to incorporate Material UI (didn't look like MUI had a specifically designated submit button).
> 
> Will continue investigating tomorrow!


Hey @cafloyd I was dealing with the same problem in my component. This seems to fix it:
```
<TextField
  id="item"
  variant="outlined"
  value={groceryItem}
  required
  onChange={updateGroceryItem}
/>

...

<MuiButton
  type="submit"
  color="primary"
  variant="contained"
>
```
You can also add logic to disable the button if your input field is empty: `disabled={groceryItem.length === 0}`.

Hope this helps.

**Comment by cafloyd** [comment]
Thank you, @dariatsvetkova !!! 💕 That did the trick!

**Review by jonathanyeong — APPROVED** [review]
Looks awesome! Love the code organization!

**Comment by luisaugusto** [comment]
Hey @cafloyd, looks good! My only feedback is that I feel these components are a little redundant since they are just wrapping the material UI components and passing the props down. With the exception of the text area being required by default, they don't provide much other value and restrict the Material UI components to specific props. My recommendation would be to directly import the Materials UI components where needed to remove the complexity of wrapper components unless we do plan on adding additional logic into them.

**Comment by cafloyd** [comment]
@luisaugusto That makes a lot of sense! I was also thinking about moving Welcome.js and ShareToken.js to the components folder. Would it make sense to do that, or maybe to leave Welcome.js where it is with the other "views", and just move ShareToken to the components folder?

**Comment by luisaugusto** [comment]
@cafloyd that's totally fine! I would probably recommend a `src/pages` directory where all your route components would be located (like the Welcome, Add Items, Item List, etc). Create React App doesn't have folder based routing but it's a very helpful paradigm to adopt regardless. Then you can add components not related to routing into the `components` folder.

**Comment by laurenmbeatty** [comment]
I really like how this is coming together ❤️

**Review by laurenmbeatty — APPROVED** [review]
LGTM 👍

**Comment by kkatoch89** [comment]
Lovin it! Thanks for doing this @cafloyd!

**Review by kkatoch89 — APPROVED** [review]

**Pull request merged**
