### PR TITLE
Added snackbar to give user feedback when item has been successfully …

### PR DESCRIPTION
**Pull request by kkatoch89**
…added to shopping list.

## Description

This feature gives user feedback that item has been successfully added

## Related Issue

issue #24 

## Acceptance Criteria

Display 'success' snackbar when user has added a new item successfully

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|  ✓ | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

### After

successfullyAdded

## Testing Steps / QA Criteria

To test the feature, use one of the following ways:
1) Follow the link to see the preview: https://tcl-22-shopping-list--pr32-kk-feedback-successf-t2vmoiog.web.app
2) Launch the app locally from your terminal:
 • Pull down this branch with `git pull origin kk-feedback-successfuly-added-item` (successfully misspelt 🙃) and check that branch out with `git checkout origin kk-feedback-successfuly-added-item`
 • Run `npm start`  to launch the app in your browser at [http://localhost:3000](http://localhost:3000)
When on application, click on 'Add Groceries' link in navbar to see user form. Fill user form and click 'Submit,'

### CODE REVIEW

**Comment by ablizben** [comment]
Oh, I like this, Karan! Awesome job.

**Review by ablizben — APPROVED** [review]

**Review by dariatsvetkova — APPROVED** [review]
Great thinking!

**Comment by cafloyd** [comment]
Fantastic, @kkatoch89! Love that the item is included in the success message, such good UX!

**Review by cafloyd — APPROVED** [review]

**Review by laurenmbeatty — APPROVED** [review]
LGTM 👍. Nice touch!

**Pull request merged**
